********************
King(a1) a2 True
King(a1) b1 True
King(a1) b2 True
********************
King(a2) a1 True
King(a2) a3 True
King(a2) b1 True
King(a2) b2 True
King(a2) b3 True
********************
King(a3) a2 True
King(a3) a4 True
King(a3) b2 True
King(a3) b3 True
King(a3) b4 True
********************
King(a4) a3 True
King(a4) a5 True
King(a4) b3 True
King(a4) b4 True
King(a4) b5 True
********************
King(a5) a4 True
King(a5) a6 True
King(a5) b4 True
King(a5) b5 True
King(a5) b6 True
********************
King(a6) a5 True
King(a6) a7 True
King(a6) b5 True
King(a6) b6 True
King(a6) b7 True
********************
King(a7) a6 True
King(a7) a8 True
King(a7) b6 True
King(a7) b7 True
King(a7) b8 True
********************
King(a8) a7 True
King(a8) b7 True
King(a8) b8 True
********************
King(b1) a1 True
King(b1) a2 True
King(b1) b2 True
King(b1) c1 True
King(b1) c2 True
********************
King(b2) a1 True
King(b2) a2 True
King(b2) a3 True
King(b2) b1 True
King(b2) b3 True
King(b2) c1 True
King(b2) c2 True
King(b2) c3 True
********************
King(b3) a2 True
King(b3) a3 True
King(b3) a4 True
King(b3) b2 True
King(b3) b4 True
King(b3) c2 True
King(b3) c3 True
King(b3) c4 True
********************
King(b4) a3 True
King(b4) a4 True
King(b4) a5 True
King(b4) b3 True
King(b4) b5 True
King(b4) c3 True
King(b4) c4 True
King(b4) c5 True
********************
King(b5) a4 True
King(b5) a5 True
King(b5) a6 True
King(b5) b4 True
King(b5) b6 True
King(b5) c4 True
King(b5) c5 True
King(b5) c6 True
********************
King(b6) a5 True
King(b6) a6 True
King(b6) a7 True
King(b6) b5 True
King(b6) b7 True
King(b6) c5 True
King(b6) c6 True
King(b6) c7 True
********************
King(b7) a6 True
King(b7) a7 True
King(b7) a8 True
King(b7) b6 True
King(b7) b8 True
King(b7) c6 True
King(b7) c7 True
King(b7) c8 True
********************
King(b8) a7 True
King(b8) a8 True
King(b8) b7 True
King(b8) c7 True
King(b8) c8 True
********************
King(c1) b1 True
King(c1) b2 True
King(c1) c2 True
King(c1) d1 True
King(c1) d2 True
********************
King(c2) b1 True
King(c2) b2 True
King(c2) b3 True
King(c2) c1 True
King(c2) c3 True
King(c2) d1 True
King(c2) d2 True
King(c2) d3 True
********************
King(c3) b2 True
King(c3) b3 True
King(c3) b4 True
King(c3) c2 True
King(c3) c4 True
King(c3) d2 True
King(c3) d3 True
King(c3) d4 True
********************
King(c4) b3 True
King(c4) b4 True
King(c4) b5 True
King(c4) c3 True
King(c4) c5 True
King(c4) d3 True
King(c4) d4 True
King(c4) d5 True
********************
King(c5) b4 True
King(c5) b5 True
King(c5) b6 True
King(c5) c4 True
King(c5) c6 True
King(c5) d4 True
King(c5) d5 True
King(c5) d6 True
********************
King(c6) b5 True
King(c6) b6 True
King(c6) b7 True
King(c6) c5 True
King(c6) c7 True
King(c6) d5 True
King(c6) d6 True
King(c6) d7 True
********************
King(c7) b6 True
King(c7) b7 True
King(c7) b8 True
King(c7) c6 True
King(c7) c8 True
King(c7) d6 True
King(c7) d7 True
King(c7) d8 True
********************
King(c8) b7 True
King(c8) b8 True
King(c8) c7 True
King(c8) d7 True
King(c8) d8 True
********************
King(d1) c1 True
King(d1) c2 True
King(d1) d2 True
King(d1) e1 True
King(d1) e2 True
********************
King(d2) c1 True
King(d2) c2 True
King(d2) c3 True
King(d2) d1 True
King(d2) d3 True
King(d2) e1 True
King(d2) e2 True
King(d2) e3 True
********************
King(d3) c2 True
King(d3) c3 True
King(d3) c4 True
King(d3) d2 True
King(d3) d4 True
King(d3) e2 True
King(d3) e3 True
King(d3) e4 True
********************
King(d4) c3 True
King(d4) c4 True
King(d4) c5 True
King(d4) d3 True
King(d4) d5 True
King(d4) e3 True
King(d4) e4 True
King(d4) e5 True
********************
King(d5) c4 True
King(d5) c5 True
King(d5) c6 True
King(d5) d4 True
King(d5) d6 True
King(d5) e4 True
King(d5) e5 True
King(d5) e6 True
********************
King(d6) c5 True
King(d6) c6 True
King(d6) c7 True
King(d6) d5 True
King(d6) d7 True
King(d6) e5 True
King(d6) e6 True
King(d6) e7 True
********************
King(d7) c6 True
King(d7) c7 True
King(d7) c8 True
King(d7) d6 True
King(d7) d8 True
King(d7) e6 True
King(d7) e7 True
King(d7) e8 True
********************
King(d8) c7 True
King(d8) c8 True
King(d8) d7 True
King(d8) e7 True
King(d8) e8 True
********************
King(e1) d1 True
King(e1) d2 True
King(e1) e2 True
King(e1) f1 True
King(e1) f2 True
********************
King(e2) d1 True
King(e2) d2 True
King(e2) d3 True
King(e2) e1 True
King(e2) e3 True
King(e2) f1 True
King(e2) f2 True
King(e2) f3 True
********************
King(e3) d2 True
King(e3) d3 True
King(e3) d4 True
King(e3) e2 True
King(e3) e4 True
King(e3) f2 True
King(e3) f3 True
King(e3) f4 True
********************
King(e4) d3 True
King(e4) d4 True
King(e4) d5 True
King(e4) e3 True
King(e4) e5 True
King(e4) f3 True
King(e4) f4 True
King(e4) f5 True
********************
King(e5) d4 True
King(e5) d5 True
King(e5) d6 True
King(e5) e4 True
King(e5) e6 True
King(e5) f4 True
King(e5) f5 True
King(e5) f6 True
********************
King(e6) d5 True
King(e6) d6 True
King(e6) d7 True
King(e6) e5 True
King(e6) e7 True
King(e6) f5 True
King(e6) f6 True
King(e6) f7 True
********************
King(e7) d6 True
King(e7) d7 True
King(e7) d8 True
King(e7) e6 True
King(e7) e8 True
King(e7) f6 True
King(e7) f7 True
King(e7) f8 True
********************
King(e8) d7 True
King(e8) d8 True
King(e8) e7 True
King(e8) f7 True
King(e8) f8 True
********************
King(f1) e1 True
King(f1) e2 True
King(f1) f2 True
King(f1) g1 True
King(f1) g2 True
********************
King(f2) e1 True
King(f2) e2 True
King(f2) e3 True
King(f2) f1 True
King(f2) f3 True
King(f2) g1 True
King(f2) g2 True
King(f2) g3 True
********************
King(f3) e2 True
King(f3) e3 True
King(f3) e4 True
King(f3) f2 True
King(f3) f4 True
King(f3) g2 True
King(f3) g3 True
King(f3) g4 True
********************
King(f4) e3 True
King(f4) e4 True
King(f4) e5 True
King(f4) f3 True
King(f4) f5 True
King(f4) g3 True
King(f4) g4 True
King(f4) g5 True
********************
King(f5) e4 True
King(f5) e5 True
King(f5) e6 True
King(f5) f4 True
King(f5) f6 True
King(f5) g4 True
King(f5) g5 True
King(f5) g6 True
********************
King(f6) e5 True
King(f6) e6 True
King(f6) e7 True
King(f6) f5 True
King(f6) f7 True
King(f6) g5 True
King(f6) g6 True
King(f6) g7 True
********************
King(f7) e6 True
King(f7) e7 True
King(f7) e8 True
King(f7) f6 True
King(f7) f8 True
King(f7) g6 True
King(f7) g7 True
King(f7) g8 True
********************
King(f8) e7 True
King(f8) e8 True
King(f8) f7 True
King(f8) g7 True
King(f8) g8 True
********************
King(g1) f1 True
King(g1) f2 True
King(g1) g2 True
King(g1) h1 True
King(g1) h2 True
********************
King(g2) f1 True
King(g2) f2 True
King(g2) f3 True
King(g2) g1 True
King(g2) g3 True
King(g2) h1 True
King(g2) h2 True
King(g2) h3 True
********************
King(g3) f2 True
King(g3) f3 True
King(g3) f4 True
King(g3) g2 True
King(g3) g4 True
King(g3) h2 True
King(g3) h3 True
King(g3) h4 True
********************
King(g4) f3 True
King(g4) f4 True
King(g4) f5 True
King(g4) g3 True
King(g4) g5 True
King(g4) h3 True
King(g4) h4 True
King(g4) h5 True
********************
King(g5) f4 True
King(g5) f5 True
King(g5) f6 True
King(g5) g4 True
King(g5) g6 True
King(g5) h4 True
King(g5) h5 True
King(g5) h6 True
********************
King(g6) f5 True
King(g6) f6 True
King(g6) f7 True
King(g6) g5 True
King(g6) g7 True
King(g6) h5 True
King(g6) h6 True
King(g6) h7 True
********************
King(g7) f6 True
King(g7) f7 True
King(g7) f8 True
King(g7) g6 True
King(g7) g8 True
King(g7) h6 True
King(g7) h7 True
King(g7) h8 True
********************
King(g8) f7 True
King(g8) f8 True
King(g8) g7 True
King(g8) h7 True
King(g8) h8 True
********************
King(h1) g1 True
King(h1) g2 True
King(h1) h2 True
********************
King(h2) g1 True
King(h2) g2 True
King(h2) g3 True
King(h2) h1 True
King(h2) h3 True
********************
King(h3) g2 True
King(h3) g3 True
King(h3) g4 True
King(h3) h2 True
King(h3) h4 True
********************
King(h4) g3 True
King(h4) g4 True
King(h4) g5 True
King(h4) h3 True
King(h4) h5 True
********************
King(h5) g4 True
King(h5) g5 True
King(h5) g6 True
King(h5) h4 True
King(h5) h6 True
********************
King(h6) g5 True
King(h6) g6 True
King(h6) g7 True
King(h6) h5 True
King(h6) h7 True
********************
King(h7) g6 True
King(h7) g7 True
King(h7) g8 True
King(h7) h6 True
King(h7) h8 True
********************
King(h8) g7 True
King(h8) g8 True
King(h8) h7 True