********************
Knight(a1) b3 True
Knight(a1) c2 True
********************
Knight(a2) b4 True
Knight(a2) c1 True
Knight(a2) c3 True
********************
Knight(a3) b1 True
Knight(a3) b5 True
Knight(a3) c2 True
Knight(a3) c4 True
********************
Knight(a4) b2 True
Knight(a4) b6 True
Knight(a4) c3 True
Knight(a4) c5 True
********************
Knight(a5) b3 True
Knight(a5) b7 True
Knight(a5) c4 True
Knight(a5) c6 True
********************
Knight(a6) b4 True
Knight(a6) b8 True
Knight(a6) c5 True
Knight(a6) c7 True
********************
Knight(a7) b5 True
Knight(a7) c6 True
Knight(a7) c8 True
********************
Knight(a8) b6 True
Knight(a8) c7 True
********************
Knight(b1) a3 True
Knight(b1) c3 True
Knight(b1) d2 True
********************
Knight(b2) a4 True
Knight(b2) c4 True
Knight(b2) d1 True
Knight(b2) d3 True
********************
Knight(b3) a1 True
Knight(b3) a5 True
Knight(b3) c1 True
Knight(b3) c5 True
Knight(b3) d2 True
Knight(b3) d4 True
********************
Knight(b4) a2 True
Knight(b4) a6 True
Knight(b4) c2 True
Knight(b4) c6 True
Knight(b4) d3 True
Knight(b4) d5 True
********************
Knight(b5) a3 True
Knight(b5) a7 True
Knight(b5) c3 True
Knight(b5) c7 True
Knight(b5) d4 True
Knight(b5) d6 True
********************
Knight(b6) a4 True
Knight(b6) a8 True
Knight(b6) c4 True
Knight(b6) c8 True
Knight(b6) d5 True
Knight(b6) d7 True
********************
Knight(b7) a5 True
Knight(b7) c5 True
Knight(b7) d6 True
Knight(b7) d8 True
********************
Knight(b8) a6 True
Knight(b8) c6 True
Knight(b8) d7 True
********************
Knight(c1) a2 True
Knight(c1) b3 True
Knight(c1) d3 True
Knight(c1) e2 True
********************
Knight(c2) a1 True
Knight(c2) a3 True
Knight(c2) b4 True
Knight(c2) d4 True
Knight(c2) e1 True
Knight(c2) e3 True
********************
Knight(c3) a2 True
Knight(c3) a4 True
Knight(c3) b1 True
Knight(c3) b5 True
Knight(c3) d1 True
Knight(c3) d5 True
Knight(c3) e2 True
Knight(c3) e4 True
********************
Knight(c4) a3 True
Knight(c4) a5 True
Knight(c4) b2 True
Knight(c4) b6 True
Knight(c4) d2 True
Knight(c4) d6 True
Knight(c4) e3 True
Knight(c4) e5 True
********************
Knight(c5) a4 True
Knight(c5) a6 True
Knight(c5) b3 True
Knight(c5) b7 True
Knight(c5) d3 True
Knight(c5) d7 True
Knight(c5) e4 True
Knight(c5) e6 True
********************
Knight(c6) a5 True
Knight(c6) a7 True
Knight(c6) b4 True
Knight(c6) b8 True
Knight(c6) d4 True
Knight(c6) d8 True
Knight(c6) e5 True
Knight(c6) e7 True
********************
Knight(c7) a6 True
Knight(c7) a8 True
Knight(c7) b5 True
Knight(c7) d5 True
Knight(c7) e6 True
Knight(c7) e8 True
********************
Knight(c8) a7 True
Knight(c8) b6 True
Knight(c8) d6 True
Knight(c8) e7 True
********************
Knight(d1) b2 True
Knight(d1) c3 True
Knight(d1) e3 True
Knight(d1) f2 True
********************
Knight(d2) b1 True
Knight(d2) b3 True
Knight(d2) c4 True
Knight(d2) e4 True
Knight(d2) f1 True
Knight(d2) f3 True
********************
Knight(d3) b2 True
Knight(d3) b4 True
Knight(d3) c1 True
Knight(d3) c5 True
Knight(d3) e1 True
Knight(d3) e5 True
Knight(d3) f2 True
Knight(d3) f4 True
********************
Knight(d4) b3 True
Knight(d4) b5 True
Knight(d4) c2 True
Knight(d4) c6 True
Knight(d4) e2 True
Knight(d4) e6 True
Knight(d4) f3 True
Knight(d4) f5 True
********************
Knight(d5) b4 True
Knight(d5) b6 True
Knight(d5) c3 True
Knight(d5) c7 True
Knight(d5) e3 True
Knight(d5) e7 True
Knight(d5) f4 True
Knight(d5) f6 True
********************
Knight(d6) b5 True
Knight(d6) b7 True
Knight(d6) c4 True
Knight(d6) c8 True
Knight(d6) e4 True
Knight(d6) e8 True
Knight(d6) f5 True
Knight(d6) f7 True
********************
Knight(d7) b6 True
Knight(d7) b8 True
Knight(d7) c5 True
Knight(d7) e5 True
Knight(d7) f6 True
Knight(d7) f8 True
********************
Knight(d8) b7 True
Knight(d8) c6 True
Knight(d8) e6 True
Knight(d8) f7 True
********************
Knight(e1) c2 True
Knight(e1) d3 True
Knight(e1) f3 True
Knight(e1) g2 True
********************
Knight(e2) c1 True
Knight(e2) c3 True
Knight(e2) d4 True
Knight(e2) f4 True
Knight(e2) g1 True
Knight(e2) g3 True
********************
Knight(e3) c2 True
Knight(e3) c4 True
Knight(e3) d1 True
Knight(e3) d5 True
Knight(e3) f1 True
Knight(e3) f5 True
Knight(e3) g2 True
Knight(e3) g4 True
********************
Knight(e4) c3 True
Knight(e4) c5 True
Knight(e4) d2 True
Knight(e4) d6 True
Knight(e4) f2 True
Knight(e4) f6 True
Knight(e4) g3 True
Knight(e4) g5 True
********************
Knight(e5) c4 True
Knight(e5) c6 True
Knight(e5) d3 True
Knight(e5) d7 True
Knight(e5) f3 True
Knight(e5) f7 True
Knight(e5) g4 True
Knight(e5) g6 True
********************
Knight(e6) c5 True
Knight(e6) c7 True
Knight(e6) d4 True
Knight(e6) d8 True
Knight(e6) f4 True
Knight(e6) f8 True
Knight(e6) g5 True
Knight(e6) g7 True
********************
Knight(e7) c6 True
Knight(e7) c8 True
Knight(e7) d5 True
Knight(e7) f5 True
Knight(e7) g6 True
Knight(e7) g8 True
********************
Knight(e8) c7 True
Knight(e8) d6 True
Knight(e8) f6 True
Knight(e8) g7 True
********************
Knight(f1) d2 True
Knight(f1) e3 True
Knight(f1) g3 True
Knight(f1) h2 True
********************
Knight(f2) d1 True
Knight(f2) d3 True
Knight(f2) e4 True
Knight(f2) g4 True
Knight(f2) h1 True
Knight(f2) h3 True
********************
Knight(f3) d2 True
Knight(f3) d4 True
Knight(f3) e1 True
Knight(f3) e5 True
Knight(f3) g1 True
Knight(f3) g5 True
Knight(f3) h2 True
Knight(f3) h4 True
********************
Knight(f4) d3 True
Knight(f4) d5 True
Knight(f4) e2 True
Knight(f4) e6 True
Knight(f4) g2 True
Knight(f4) g6 True
Knight(f4) h3 True
Knight(f4) h5 True
********************
Knight(f5) d4 True
Knight(f5) d6 True
Knight(f5) e3 True
Knight(f5) e7 True
Knight(f5) g3 True
Knight(f5) g7 True
Knight(f5) h4 True
Knight(f5) h6 True
********************
Knight(f6) d5 True
Knight(f6) d7 True
Knight(f6) e4 True
Knight(f6) e8 True
Knight(f6) g4 True
Knight(f6) g8 True
Knight(f6) h5 True
Knight(f6) h7 True
********************
Knight(f7) d6 True
Knight(f7) d8 True
Knight(f7) e5 True
Knight(f7) g5 True
Knight(f7) h6 True
Knight(f7) h8 True
********************
Knight(f8) d7 True
Knight(f8) e6 True
Knight(f8) g6 True
Knight(f8) h7 True
********************
Knight(g1) e2 True
Knight(g1) f3 True
Knight(g1) h3 True
********************
Knight(g2) e1 True
Knight(g2) e3 True
Knight(g2) f4 True
Knight(g2) h4 True
********************
Knight(g3) e2 True
Knight(g3) e4 True
Knight(g3) f1 True
Knight(g3) f5 True
Knight(g3) h1 True
Knight(g3) h5 True
********************
Knight(g4) e3 True
Knight(g4) e5 True
Knight(g4) f2 True
Knight(g4) f6 True
Knight(g4) h2 True
Knight(g4) h6 True
********************
Knight(g5) e4 True
Knight(g5) e6 True
Knight(g5) f3 True
Knight(g5) f7 True
Knight(g5) h3 True
Knight(g5) h7 True
********************
Knight(g6) e5 True
Knight(g6) e7 True
Knight(g6) f4 True
Knight(g6) f8 True
Knight(g6) h4 True
Knight(g6) h8 True
********************
Knight(g7) e6 True
Knight(g7) e8 True
Knight(g7) f5 True
Knight(g7) h5 True
********************
Knight(g8) e7 True
Knight(g8) f6 True
Knight(g8) h6 True
********************
Knight(h1) f2 True
Knight(h1) g3 True
********************
Knight(h2) f1 True
Knight(h2) f3 True
Knight(h2) g4 True
********************
Knight(h3) f2 True
Knight(h3) f4 True
Knight(h3) g1 True
Knight(h3) g5 True
********************
Knight(h4) f3 True
Knight(h4) f5 True
Knight(h4) g2 True
Knight(h4) g6 True
********************
Knight(h5) f4 True
Knight(h5) f6 True
Knight(h5) g3 True
Knight(h5) g7 True
********************
Knight(h6) f5 True
Knight(h6) f7 True
Knight(h6) g4 True
Knight(h6) g8 True
********************
Knight(h7) f6 True
Knight(h7) f8 True
Knight(h7) g5 True
********************
Knight(h8) f7 True
Knight(h8) g6 True