None
[Errno 2] No such file or directory: 'file1.txt'
None
[Errno 2] No such file or directory: 'file2.txt'
None
[Errno 2] No such file or directory: 'file3.txt'
None
[Errno 2] No such file or directory: 'file4.txt'
None
[Errno 2] No such file or directory: 'file5.txt'
None
[Errno 2] No such file or directory: 'file6.txt'
None
[Errno 2] No such file or directory: 'file7.txt'
None
[Errno 2] No such file or directory: 'file8.txt'
None
[Errno 2] No such file or directory: 'file9.txt'
None
[Errno 2] No such file or directory: 'file10.txt'
None
[Errno 2] No such file or directory: 'file11.txt'
None
[Errno 2] No such file or directory: 'file12.txt'
None
[Errno 2] No such file or directory: 'file13.txt'
None
[Errno 2] No such file or directory: 'file14.txt'
None
[Errno 2] No such file or directory: 'file15.txt'
None
[Errno 2] No such file or directory: 'file16.txt'
None
[Errno 2] No such file or directory: 'file17.txt'
None
[Errno 2] No such file or directory: 'file18.txt'
None
[Errno 2] No such file or directory: 'file19.txt'
None
[Errno 2] No such file or directory: 'file20.txt'